version: "3"

services:
    lb:
        image: kioshiokamoto/haproxy:7.0
        container_name: load-balancer
        restart: always
        mem_limit: 200m
        mem_reservation: 128M
        cpus: 0.5
        ports:
            - "5000:5000"
    client:
        image: kioshiokamoto/frontend-next-demo:2.0
        container_name: frontend
        restart: always
        mem_limit: 500m
        mem_reservation: 128M
        cpus: 0.7
        ports:
            - "3000:3000"
        environment:
            API_BASE_URL: $API_BASE_URL
            NEXT_PUBLIC_API_BASE_URL: $NEXT_PUBLIC_API_BASE_URL
        links:
            - lb
