version: "3"
services:
    app-1:
        image: kioshiokamoto/backend-nodejs-demo:5.0
        container_name: proj-node-1
        restart: always
        mem_limit: 200m
        mem_reservation: 128M
        cpus: 0.25
        env_file:
            - ./.env
        environment:
            - PORT=5001
            - MONGODB_URL=$MONGODB_URL
            - ACTIVATION_TOKEN_SECRET=$ACTIVATION_TOKEN_SECRET
            - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
            - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
            - CLIENT_URL=$CLIENT_URL
            - MAILING_SERVICE_CLIENT_ID=$MAILING_SERVICE_CLIENT_ID
            - MAILING_SERVICE_CLIENT_SECRET=$MAILING_SERVICE_CLIENT_SECRET
            - MAILING_SERVICE_REFRESH_TOKEN=$MAILING_SERVICE_REFRESH_TOKEN
            - SENDER_EMAIL_ADDRESS=$SENDER_EMAIL_ADDRESS
            - CLOUD_NAME=$CLOUD_NAME
            - CLOUD_API_KEY=$CLOUD_API_KEY
            - CLOUD_API_SECRET=$CLOUD_API_SECRET
            - GOOGLE_SECRET=$GOOGLE_SECRET
            - FACEBOOK_SECRET=$FACEBOOK_SECRET
        ports:
            - "5001:5001"
        # links:
        #     - mongo
    app-2:
        image: kioshiokamoto/backend-nodejs-demo:5.0
        container_name: proj-node-2
        restart: always
        mem_limit: 200m
        mem_reservation: 128M
        cpus: 0.25
        env_file: ./.env
        environment:
            - PORT=5002
            - MONGODB_URL=$MONGODB_URL
            - ACTIVATION_TOKEN_SECRET=$ACTIVATION_TOKEN_SECRET
            - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
            - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
            - CLIENT_URL=$CLIENT_URL
            - MAILING_SERVICE_CLIENT_ID=$MAILING_SERVICE_CLIENT_ID
            - MAILING_SERVICE_CLIENT_SECRET=$MAILING_SERVICE_CLIENT_SECRET
            - MAILING_SERVICE_REFRESH_TOKEN=$MAILING_SERVICE_REFRESH_TOKEN
            - SENDER_EMAIL_ADDRESS=$SENDER_EMAIL_ADDRESS
            - CLOUD_NAME=$CLOUD_NAME
            - CLOUD_API_KEY=$CLOUD_API_KEY
            - CLOUD_API_SECRET=$CLOUD_API_SECRET
            - GOOGLE_SECRET=$GOOGLE_SECRET
            - FACEBOOK_SECRET=$FACEBOOK_SECRET
        ports:
            - "5002:5002"
        # links:
        #     - mongo
    app-3:
        image: kioshiokamoto/backend-nodejs-demo:5.0
        container_name: proj-node-3
        restart: always
        mem_limit: 200m
        mem_reservation: 128M
        cpus: 0.25
        env_file: ./.env
        environment:
            - PORT=5003
            - MONGODB_URL=$MONGODB_URL
            - ACTIVATION_TOKEN_SECRET=$ACTIVATION_TOKEN_SECRET
            - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
            - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
            - CLIENT_URL=$CLIENT_URL
            - MAILING_SERVICE_CLIENT_ID=$MAILING_SERVICE_CLIENT_ID
            - MAILING_SERVICE_CLIENT_SECRET=$MAILING_SERVICE_CLIENT_SECRET
            - MAILING_SERVICE_REFRESH_TOKEN=$MAILING_SERVICE_REFRESH_TOKEN
            - SENDER_EMAIL_ADDRESS=$SENDER_EMAIL_ADDRESS
            - CLOUD_NAME=$CLOUD_NAME
            - CLOUD_API_KEY=$CLOUD_API_KEY
            - CLOUD_API_SECRET=$CLOUD_API_SECRET
            - GOOGLE_SECRET=$GOOGLE_SECRET
            - FACEBOOK_SECRET=$FACEBOOK_SECRET
        ports:
            - "5003:5003"
