version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
  app:
    container_name: proj_node
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    links:
      - mongo
  client:
    container_name: frontend
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app
